config:
  security:
    oauth:
      client:
        id: back
        secret: 123456
      jwt:
        key: pantro_chitara_felino_tigro_carlota_inquilino

spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://server-zipkin:9411/
    sender:
      type: rabbit
  rabbitmq:
    host: microservicios-rabbitmq